v1=c(1,2,3,4,5,6,7,8,9)
v2=c(letters[1:9])
m1=matrix(v1,nrow = 3,byrow = TRUE)
m2=matrix(v2,nrow = 3,byrow = TRUE)
print(m2)
print("Second row of second matrix :")
print(m2[2,])
print("Third row of first matrix :")
print(m1[3,])
print("Third column of first matrix :")
print(m1[,3])