library(reshape)
countries=c("A","B","C")
value.popululation_in_millions=c(100,200,120)
value.gdp_percaptita=c(2000,7000,15000)
df=data.frame(countries,value.popululation_in_millions,value.gdp_percaptita)
print("Original dataframe :")
print(df)
print("After reshaping long :")
m=melt.data.frame(df)
print(m)
print("After reshaping wide :")
print(cast(m))